spring:
  ai:
    mcp:
      server:
        name: dungeons-and-dragons-mcp
        version: 1.0.0
        type: SYNC
        instructions: "This server provides information from the Dungeons and Dragons 5e SRD"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
  application:
    name: dnd-5e-api
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 5e-database
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  graphql:
    graphiql:
      enabled: true
  jackson:
    default-property-inclusion: non_null