package com.thejaxonhill.dnd5eapi.characterclass.infrastructure.persistence

import com.thejaxonhill.dnd5eapi.shared.infrastructure.persistence.repository.IndexedMongoRepository

interface CharacterClassMongoRepository : IndexedMongoRepository<CharacterClassDocument, String>