package com.thejaxonhill.dnd5eapi.magicitem.infrastructure.persistence

import com.thejaxonhill.dnd5eapi.shared.infrastructure.persistence.repository.IndexedMongoRepository

interface MagicItemMongoRepository : IndexedMongoRepository<MagicItemDocument, String>