package com.thejaxonhill.dnd5eapi.equipment.application.dto

import com.thejaxonhill.dnd5eapi.equipment.domain.model.*
import com.thejaxonhill.dnd5eapi.shared.domain.model.ApiReference
import com.thejaxonhill.dnd5eapi.shared.domain.model.Damage

data class EquipmentView(
    val armorCategory: String? = null,
    val armorClass: ArmorClass? = null,
    val capacity: String? = null,
    val categoryRange: String? = null,
    val contents: List<Content>? = null,
    val cost: Cost,
    val damage: Damage? = null,
    val desc: String? = null,
    val equipmentCategory: ApiReference,
    val gearCategory: ApiReference? = null,
    val index: String,
    val name: String,
    val properties: List<ApiReference>? = null,
    val quantity: Int? = null,
    val range: Range? = null,
    val special: List<String>? = null,
    val speed: Speed? = null,
    val stealthDisadvantage: Boolean? = null,
    val strMinimum: Int? = null,
    val throwRange: ThrowRange? = null,
    val toolCategory: String? = null,
    val twoHandedDamage: TwoHandedDamage? = null,
    val vehicleCategory: String? = null,
    val weaponCategory: String? = null,
    val weaponRange: String? = null,
    val weight: Double? = null,
    val url: String,
)

fun Equipment.toView() = EquipmentView(
    armorCategory = armorCategory,
    armorClass = armorClass,
    capacity = capacity,
    categoryRange = categoryRange,
    contents = contents,
    cost = cost,
    damage = damage,
    desc = desc,
    equipmentCategory = equipmentCategory,
    gearCategory = gearCategory,
    index = index,
    name = name,
    properties = properties,
    quantity = quantity,
    range = range,
    special = special,
    speed = speed,
    stealthDisadvantage = stealthDisadvantage,
    strMinimum = strMinimum,
    throwRange = throwRange,
    toolCategory = toolCategory,
    twoHandedDamage = twoHandedDamage,
    vehicleCategory = vehicleCategory,
    weaponCategory = weaponCategory,
    weaponRange = weaponRange,
    weight = weight,
    url = url,
)
