package com.thejaxonhill.dnd5eapi.damagetype.infrastructure.persistence

import com.thejaxonhill.dnd5eapi.shared.infrastructure.persistence.repository.IndexedMongoRepository

interface DamageTypeMongoRepository : IndexedMongoRepository<DamageTypeDocument, String>