package com.thejaxonhill.dnd5eapi.alignment.infrastructure.persistence

import com.thejaxonhill.dnd5eapi.shared.infrastructure.persistence.repository.IndexedMongoRepository

interface AlignmentMongoRepository : IndexedMongoRepository<AlignmentDocument, String>