package com.thejaxonhill.dnd5eapi.level.domain.model

data class ClassSpecific(
    val actionSurges: Int? = null,
    val arcaneRecoveryLevels: Int? = null,
    val auraRange: Long? = null,
    val bardicInspirationDie: Int? = null,
    val brutalCriticalDice: Int? = null,
    val channelDivinityCharges: Int? = null,
    val creatingSpellSlots: List<ClassSpecificCreatingSpellSlot>? = null,
    val destroyUndeadCr: Int? = null,
    val extraAttacks: Int? = null,
    val favoredEnemies: Int? = null,
    val favoredTerrain: Int? = null,
    val indomitableUses: Int? = null,
    val invocationsKnown: Int? = null,
    val kiPoints: Int? = null,
    val magicalSecretsMax5: Int? = null,
    val magicalSecretsMax7: Int? = null,
    val magicalSecretsMax9: Int? = null,
    val martialArts: ClassSpecificMartialArt? = null,
    val metamagicKnown: Int? = null,
    val mysticArcanumLevel6: Int? = null,
    val mysticArcanumLevel7: Int? = null,
    val mysticArcanumLevel8: Int? = null,
    val mysticArcanumLevel9: Int? = null,
    val rageCount: Int? = null,
    val rageDamageBonus: Int? = null,
    val sneakAttack: ClassSpecificSneakAttack? = null,
    val songOfRestDie: Int? = null,
    val sorceryPoints: Int? = null,
    val unarmoredMovement: Long? = null,
    val wildShapeFly: Boolean? = null,
    val wildShapeMaxCr: Int? = null,
    val wildShapeSwim: Boolean? = null,
)
