package com.thejaxonhill.dnd5eapi.magicschool.infrastructure.persistence

import com.thejaxonhill.dnd5eapi.shared.infrastructure.persistence.repository.IndexedMongoRepository

interface MagicSchoolMongoRepository : IndexedMongoRepository<MagicSchoolDocument, String>