package com.thejaxonhill.dnd5eapi.equipmentcategory.persistence

import com.thejaxonhill.dnd5eapi.shared.persistence.IndexedMongoRepository

interface EquipmentCategoryRepository : IndexedMongoRepository<EquipmentCategoryDocument, String>